<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EJHI608" failures="1" tests="5" name="Test" time="4.907" errors="0" timestamp="2023-12-28T23:18:50 IST">
  <testcase classname="testcases.TestBrowsers" name="testCase1" time="4.833"/>
  <testcase classname="testcases.TestBrowsers" name="fourthTest" time="0.007"/>
  <testcase classname="testcases.TestBrowsers" name="secondTest" time="0.001"/>
  <testcase classname="testcases.TestBrowsers" name="thirdTest" time="0.003"/>
  <testcase classname="testcases.ListenerDemo" name="login" time="0.003">
    <failure type="java.lang.AssertionError" message="Failing the test deliberately">
      <![CDATA[java.lang.AssertionError: Failing the test deliberately
at testcases.ListenerDemo.login(ListenerDemo.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
